apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: couchdb
  name: couchdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.18.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: couchdb
    spec:
      containers:
      - env:
        - name: NODENAME
          value: couchdb.hsm.com
        image: couchdb:latest
        name: couchdb
        resources: {}
        volumeMounts:
        - mountPath: /opt/couchdb/etc/local.d/20-cluster.ini
          name: couchdb-claim0
        - mountPath: /opt/couchdb/data
          name: couchdb-data
      hostname: couchdb.hsm.com
      restartPolicy: Always
      volumes:
      - name: couchdb-claim0
        persistentVolumeClaim:
          claimName: couchdb-claim0
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-data
status: {}
