apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mailcatcher
  name: mailcatcher
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.18.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mailcatcher
    spec:
      containers:
      - image: schickling/mailcatcher
        name: mailcatcher
        resources: {}
      hostname: mail.hsm.com
      restartPolicy: Always
status: {}
