ARG OTP_VERSION=23.3.4.11
FROM erlang:${OTP_VERSION}

ENV OTP_VERSION ${OTP_VERSION:-23.3.4.11}

ENV DEBIAN_FRONTEND=noninteractive
ENV APT_LISTCHANGES_FRONTEND=none

## apt-transport-https is needed because CouchDB repo is https
RUN printf "\n\n:: Using erlang:@$OTP_VERSION\n\n\n" \
    && echo ":: Locales and others" \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        apt-transport-https \
        locales gnupg \
    \
    ## Adding CouchDB repo and GPG key
    && echo ":: Setting up good repos" \
    ## bcc needs netprefs as build dependency which is non-free
    && sed -r -i 's/(stretch.*main)$/\1 non-free/g' /etc/apt/sources.list \
    \
    && echo ":: Adding CouchDB repo" \
    && case "$OTP_VERSION" in \
           22*) \
             echo "it is buster" \
             && (echo "deb https://apache.bintray.com/couchdb-deb buster main" | tee -a /etc/apt/sources.list) \
             && (curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | apt-key add -) \
             ;; \
           *) \
             echo "it is stretch" \
             && (echo "deb https://apache.bintray.com/couchdb-deb stretch main" | tee -a /etc/apt/sources.list) \
             && (curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | apt-key add -) \
             ;; \
       esac \
    \
    # && echo ":: Adding LLVM repo" \
    # && echo >> /etc/apt/sources.list \
    # && echo '# LLVM repo (in hope to add bcc & bpftrace later)' >> /etc/apt/sources.list \
    # && (echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch main" | tee -a /etc/apt/sources.list) \
    # && (echo "deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch main" | tee -a /etc/apt/sources.list) \
    # && echo "# LLVM 8" >> /etc/apt/sources.list \
    # && (echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-8 main" | tee -a /etc/apt/sources.list) \
    # && (echo "deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-8 main" | tee -a /etc/apt/sources.list) \
    # && (curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -) \
    \
    && echo ":: Set timezone to UTC by default" \
    && sed -i 's/# en_US\.UTF-8/en_US.UTF-8/g' /etc/locale.gen \
    && ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime \
    && locale-gen en_US.UTF-8 \
    && echo "$OTP_VERSION" > /otp_version \
    \
    ## Install build time tools and some other utilities
    && echo ":: Install them all!" \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        ## editors and tools
        neovim emacs-nox ctags bash-completion tmux \
        silversearcher-ag jq colordiff htop \
        ## useful tools
        man sudo less whois strace tcpdump net-tools ntpdate dnsutils psmisc lsof \
        ## Kazoo runtime dependencies
        zip unzip libexpat1-dev htmldoc sox libsox-fmt-all ghostscript \
        imagemagick libtiff-tools openjdk-11-jre libreoffice-writer \
        ## Docs dependencies
        mkdocs python-pip python3-pip cpio \
        python-yaml python-markdown python-jsonschema \
        python3-yaml python3-markdown python3-jsonschema \
        ## validate-js dependencies
        couchdb \
        python3-jsbeautifier \
        ## performance tools
        perf-tools-unstable \
        ## WeasyPrint dependencies
        python3-dev python3-setuptools python3-wheel python3-cffi \
        fonts-roboto fonts-liberation2 fonts-lato \
    \
    && echo ":: Setup sudo" \
    && echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && visudo -c -f /etc/sudoers \
    \
    && echo ":: Cleanup!!" \
    && rm -rf /tmp/* \
    && rm -rf /var/lib/apt/lists/*

ENV LANG en_US.UTF-8

RUN echo ":: Install nvim and docs dependencies" \
    # setuptools is needed to install python-neovim
    && pip install setuptools \
    && pip3 install setuptools \
    && pip install pynvim pyembed-markdown \
    && pip3 install pynvim pyembed-markdown \
    && pip3 install WeasyPrint \
    && ln -s /opt/couchdb/bin/couchjs /usr/bin/couchj \
    \
    && echo ":: Installing su-exec" \
    && git clone https://github.com/ncopa/su-exec.git /tmp/su-exec \
    && cd /tmp/su-exec \
    && make \
    && cp su-exec /usr/bin/su-exec \
    && rm -rf /tmp/*

RUN echo ":: Installing dotfiles" \
    && rm -rf /etc/skel \
    && mkdir -p /etc/skel \
    && (curl -L https://api.github.com/repos/icehess/dotfiles/tarball/docker-lite \
        | tar -C /etc/skel -xz --strip 1 \
       ) \
    \
    && echo ":: Installing fzf" \
    && mkdir -p /etc/skel/.fzf \
    && (curl -L https://api.github.com/repos/junegunn/fzf/tarball \
        | tar -C /etc/skel/.fzf -xz --strip 1 \
       ) \
    && /etc/skel/.fzf/install --bin \
    \
    && echo ":: Setting up nvim" \
    && HOME=/etc/skel nvim +PlugInstall +qall --cmd 'set rtp^=/etc/skel/.vim' \
    && mv /etc/skel/.dotfiles-site/files/vim/plugins/kazoo_erlc.vim \
        /etc/skel/.vim/bundle/ale/ale_linters/erlang/ \
    \
    && echo ":: Cleanup!!" \
    && for dir in /etc/skel/.vim/bundle/* ; do rm -rf $dir/.git ; done \
    && for dir in /etc/skel/.vim/bundle/*/doc ; do rm -rf $dir ; done \
    && for dir in /etc/skel/.vim/bundle/*/test; do rm -rf $dir ; done \
    && find /etc/skel/.vim/bundle/ -name *.png -exec rm {} \; \
    && find /etc/skel/.vim/bundle/ -name *.gif -exec rm {} \; \
    && find /etc/skel/.vim/bundle/ -name *.jpg -exec rm {} \; \
    && find /etc/skel/.vim/bundle/ -name *.md -exec rm {} \; \
    && find /etc/skel/.vim/bundle/ -name LICENCE -exec rm {} \; \
    \
    && echo ":: Setting up root dotfiles" \
    && rm -rf /root && cp -R /etc/skel /root

ENV LOCAL_USERNAME devuser

COPY docker-entrypoint.sh /docker-entrypoint.sh

EXPOSE 11500 8000 5555

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/bash", "--login"]
