version: '3.7'

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: 'kazoo5-mac.icehess.page'
        environment:
            # This is needed to allow distributed Erlang shell
            # and start of rabbitmq
            RABBITMQ_USE_LONGNAME: 'true'
        volumes:
            # enabling rabbitmq_consistent_hash_exchange plugin
            - type: bind
              source: ${KZ_DOCKER_DIR}/files/rabbitmq-entrypoint.sh
              target: /rabbitmq-entrypoint.sh
            # without this sometimes docker/rabbitmq veing stupid
            # and causing rabbitmq to behave strangely (not creating exchange or etc)
            - type: tmpfs
              target: /var/lib/rabbitmq
        entrypoint: /rabbitmq-entrypoint.sh
        command: ["rabbitmq-server"]
        ports:
            - target: 15672 # management UI
              published: 15672
            - target: 5672 # AMQP port
              published: 5672

    kazoo_apps:
        image: icehess/kz-dev-slim:23.3.4.18
        hostname: 'kazoo5-mac.icehess.page'
        environment:
            TERM: xterm-256color
            KAZOO_COOKIE: change_me
            FETCH_AS: 'git@github.com:'
            KAZOO_SRC: '/home/devuser/kazoo'
            KAZOO_ROOT: '/home/devuser/kazoo'
            SSH_AUTH_SOCK: /home/devuser/.host-services/ssh-auth.sock
            # KAZOO_NODE: kazoo_apps
            # NODE_NAME: kazoo_apps
            # REL: kazoo_apps
        volumes:
            ## SSH stuff
            - type: bind
              source: /run/host-services/ssh-auth.sock
              target: /home/devuser/.host-services/ssh-auth.sock
              # read_only: true

            ## Kazoo stuff
            - type: bind
              source: ${KAZOO_SRC}
              target: /home/devuser/kazoo
            - type: bind
              source: ${wKazoo}/kazoo-sounds
              target: /home/devuser/sounds
              read_only: true
            - type: bind
              source: ${wKazoo}/monster-ui
              target: /home/devuser/monster-ui
              read_only: true
            - type: tmpfs
              target: /etc/kazoo/ra

            ## Kazoo icehess runtime
            - type: bind
              source: ${KZ_DOCKER_DIR}/docker-desktop/kazoo-config.ini
              target: /etc/kazoo/config.ini

            ## docker stuff
            - type: bind
              source: ${KZ_DOCKER_DIR}/docker-desktop/docker-entrypoint-prepare
              target: /docker-entrypoint-prepare
            - type: bind
              source: ${KZ_DOCKER_DIR}/scripts
              target: /home/devuser/scripts
        tty: true
        command: ["bash"]
        ports:
            - target: 11500 # Erlang
              published: 11500
            - target: 8000 # Crossbar
              published: 8000
            - target: 5555 # Websocket
              published: 5555
            - target: 25 # Fax SMTP
