apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1RENDQWN5Z0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFqTVJBd0RnWURWUVFLRXdkck0zTXQKYjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd0hoY05NVGt3TXpJeE1qRXlPVFEzV2hjTk1qa3dNekU0TWpFeQpPVFEzV2pBak1SQXdEZ1lEVlFRS0V3ZHJNM010YjNKbk1ROHdEUVlEVlFRREV3WnJNM010WTJFd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDbnQrdUNqZStrZzdkZTU5bHUyQWNFOHJ5Mnh1M28KU1NRMWlTODRncTVoSTZKdXdBZkFnT1d6OFJSWFI1Q085cWMrVmEvcFZEdXJ1M3ZwYllISGdzUnYyYng5ZnphUwpRdTNZeVZSWXRVNEVHNDRqWEJVVElkOWxTVmI3QzMxWkZKSVlMekR3WHlKTG1jMHZJQ0FhNXRVNGtyYUVXSnpaCitISG9TMzE3RWw1TklabU9WQmkxZEtEamI2SUpFWE1heFNVTXNBeEZQRENMcVZKRGxvWk8zRFRUbFREUTdIMUEKeDF1SWJIVEZEa1R6UzArTTMzREJXdWRRZm11RDB0UTJrUDJaWnI1bEVybnpCNnhjWXpyZEd5ak5TUmZHOTBDeQp6dEUwUXBkalhqQVc1T2dEaDNvKytiSmZmWU9iQkEvYlZQUFlKY2hEVHVMeW1ITjZvSUhEblpYOUFnTUJBQUdqCkl6QWhNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUNaNGQ0VUNRMkIzMTFjSjJHdUxPaGovdEx1NkQ5M3owZUNHVHAwLytqU1YwRUZHRHUxMHpaTAoxaWdyTVhtMVA1cHlNNWtTR3I3cEhqcXhsbDU0RTlXaTJvbVZaWldkdG1hZWRLazZnZkxCT1FKR25paFJ4SlFFClJBQUlYQmhSZWVGRW1IanMyU2RPWUZxVG12VGY0MVgvQVBNWHY4Rmx1a3NwNlMyUnErNzhUQ0NKTENaQlFSTmQKTHdDZnF6WkhsRzRpWEFJRWxVc0ttVmxNeWh1MjdtdjRlakkzb1B6ZDh0eEJTd016and1UEpFSjRNQm1ZYzBZQgpacXNYa1Q5bVVRQ2hjQXdETDcwYTNUaUI1MUJjTjRzM2lCc2hTNnlQcVJpNU1sR2t1eE9zMzhTd0lLTnIyZmMxCjJUV1ZhMzlJTDFibEk0NVJyNDF6NzVQN2dzVmZGeFozCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://localhost:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 2003ec1a6b839d89c70142534787f3af
    username: admin
