version: '3.7'

x-node-env:
  &kz-env
    LOCAL_USER: "y"
    TERM: screen-256color
    KAZOO_COOKIE: change_me
    # LC_CTYPE: en_US.UTF-8
    # LANG: en_US.UTF-8
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/kazoo/_rel/kazoo/bin"

x-devnode-cfg:
  &kz-dev
    - type: bind
      source: ${KAZOO_SRC:?give me your kazoo source path}
      target: /opt/kazoo
      read_only: false
    - type: bind
      source: ${wKazoo:?err}/sounds/kazoo-core
      target: /opt/sounds
      read_only: true
    - type: bind
      source: ${wWork:?err}/dockerfiles/scripts
      target: /opt/scripts
      read_only: true
    - type: bind
      source: ${wKazoo:?err}/monster-ui
      target: /opt/monster-ui
      read_only: true

volumes:
  couchdb_data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'

configs:
  kazoo_config_ini:
      file: ${wWork:?err}/dockerfiles/kazoo/stacks/just-kz/config.ini

services:

  couchdb:
    image: couchdb:latest
    hostname: 'couchdb.{{.Task.Slot}}'
    environment:
      NODENAME: 'couchdb.{{.Task.Slot}}'
    ports:
      - target: 9100
      - target: 5984
        mode: host
      - target: 5986
        mode: host
    deploy:
      mode: replicated
    volumes:
      - type: bind
        source: ${wWork:?err}/dockerfiles/kazoo/stacks/just-kz/couchdb_cluster.ini
        target: /opt/couchdb/etc/local.d/20-cluster.ini
      - type: volume
        source: 'couchdb_data'
        target: "/opt/couchdb/data"
    networks:
      kazoo:
        aliases:
          - 'couchdb.{{.Task.Slot}}'

  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq.{{.Task.Slot}}'
    ports:
      - target: 15672 # management UI
        mode: host
      - target: 5672 # AMQP port
        mode: host
    networks:
      kazoo:
        aliases:
          - 'rabbitmq.{{.Task.Slot}}'

  kazoo_apps:
    image: icehess/kz-dev-env:19
    hostname: 'kazoo_apps.{{.Task.Slot}}'
    environment:
       << : *kz-env
       KAZOO_NODE: kazoo_apps
       NODE_NAME: kazoo_apps
       REL: kazoo_apps
    volumes: *kz-dev
    configs:
      - source: kazoo_config_ini
        target: /etc/kazoo/config.ini
    ports:
      - target: 11500 # Erlang
        mode: host
      - target: 8000 # Crossbar
        mode: host
      - target: 5555 # Websocket
        mode: host
      - target: 25 # Fax SMTP
        mode: host
      - target: 8001 # GraphQL
        mode: host
    tty: true
    command: ["bash"]
    networks:
      kazoo:
        aliases:
          - 'kazoo_apps.{{.Task.Slot}}'

  # kazoo_ecallmgr:
  #   image: icehess/kz-dev-env:19
  #   hostname: 'kazoo_ecallmgr.{{.Task.Slot}}'
  #   environment:
  #      << : *kz-env
  #      KAZOO_NODE: ecallmgr
  #      NODE_NAME: ecallmgr
  #      REL: ecallmgr
  #      KAZOO_APPS: "ecallmgr"
  #   volumes: *kz-dev
  #   configs:
  #     - source: kazoo_config_ini
  #       target: /etc/kazoo/config.ini
  #   ports:
  #     - target: 11500
  #       mode: host
  #   command: ["bash"]
  #   tty: true
  #   networks:
  #     kazoo:
  #       aliases:
  #         - 'kazoo_ecallmgr.{{.Task.Slot}}'

  monster-ui:
    image: node:8.11.3-stretch
    hostname: 'monster-ui.{{.Task.Slot}}'
    environment:
       TERM: screen-256color
       LC_CTYPE: en_US.UTF-8
       LANG: en_US.UTF-8
    volumes:
      - type: bind
        source: ./monster-entrypoint.sh
        target: /monster-entrypoint.sh
      - type: bind
        source: ${wKazoo:?err}/monster-ui
        target: "/opt/monster-ui"
      - type: bind
        source: ${wKazoo:?err}/su-exec/su-exec
        target: "/su-exec"
    ports:
      - target: 3000
        mode: host
    tty: true
    entrypoint: /monster-entrypoint.sh
    command: ["/opt/monster-ui/node_modules/gulp/bin/gulp.js"]
    networks:
      kazoo:
        aliases:
          - 'monster-ui.{{.Task.Slot}}'

  # mailhog:
  #   image: 'mailhog/mailhog:latest'
  #   hostname: 'mailcatcher'
  #   ports:
  #     - target: 8025
  #       mode: host
  #     - target: 1025
  #       mode: host
  #   networks:
  #     - kazoo

  mailcatcher:
    image: 'schickling/mailcatcher'
    ports:
      - target: 1080
        mode: host
      - target: 1025
        mode: host
    networks:
      - kazoo

networks:
  # kazoo_public:
  #   external: true
  #   name: host
  kazoo:
    attachable: true

