version: '3.5'

x-node-env:
  &kz-env
    TERM: screen-256color
    KAZOO_COOKIE: change_me
    LC_CTYPE: en_US.UTF-8
    LANG: en_US.UTF-8
    CODE_LOADING_MODE: interactive
    RELX_REPLACE_OS_VARS: "true"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/kazoo/_rel/kazoo/bin"

x-devnode-cfg:
  &kz-dev
    - type: bind
      source: ${KAZOO_SRC_PATH:-/home/hesaam/work/2600hz/kazoo/master}
      target: /opt/kazoo
      read_only: false
    - type: bind
      source: ${KAZOO_SOUNDS_PATH:-/home/hesaam/work/2600hz/kazoo/sounds/kazoo-core}
      target: /opt/sounds
      read_only: true

volumes:
  couchdb_data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'

configs:
  kazoo_config_ini:
    file: ./config.ini
  couchdb_cluster_ini:
    file: ./couchdb_cluster.ini

services:

  couchdb:
    image: couchdb:latest
    hostname: 'couchdb.{{.Task.Slot}}'
    environment:
      NODENAME: 'couchdb.{{.Task.Slot}}'
    ports:
      - target: 9100
      - target: 5984
      - target: 5986
    deploy:
      mode: replicated
    configs:
      - source: couchdb_cluster_ini
        target: /opt/couchdb/etc/local.d/cluster.ini
        uid: '5984'
        gid: '5984'
    volumes:
      - type: volume
        source: 'couchdb_data'
        target: "/opt/couchdb/data"
    networks:
      kazoo:
        aliases:
          - 'couchdb.{{.Task.Slot}}'

  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq.{{.Task.Slot}}'
    ports:
      - target: 15672 # management UI
      - target: 5672 # AMQP port
    networks:
      kazoo:
        aliases:
          - 'rabbitmq.{{.Task.Slot}}'

  kazoo_apps:
    image: ${KZ_DEV_BASE_IMAGE:-kz-dev-base:20}
    hostname: 'kazoo_apps.{{.Task.Slot}}'
    environment:
       << : *kz-env
       KAZOO_NODE: kazoo_apps
       NODE_NAME: kazoo_apps
       REL: kazoo_apps
    volumes: *kz-dev
    configs:
      - source: kazoo_config_ini
        target: /etc/kazoo/config.ini
    ports:
      - target: 11500
      - target: 8000
      - target: 5555
      - target: 8001 # GraphQL
    tty: true
    command: ["bash"]
    networks:
      kazoo:
        aliases:
          - 'kazoo_apps.{{.Task.Slot}}'

  # kazoo_ecallmgr:
  #   image: ${KZ_DEV_BASE_IMAGE:-kz-dev-base}
  #   hostname: 'kazoo_ecallmgr.{{.Task.Slot}}'
  #   environment:
  #      << : *kz-env
  #      KAZOO_NODE: ecallmgr
  #      NODE_NAME: ecallmgr
  #      REL: ecallmgr
  #      KAZOO_APPS: "ecallmgr"
  #   volumes: *kz-dev
  #   configs:
  #     - source: kazoo_config_ini
  #       target: /etc/kazoo/config.ini
  #   ports:
  #     - target: 11500
  #   command: ["bash"]
  #   tty: true
  #   networks:
  #     kazoo:
  #       aliases:
  #         - 'kazoo_ecallmgr.{{.Task.Slot}}'

  monster-ui:
    image: ${MONSTER_IMG:-node:8.11.3-stretch}
    hostname: 'monster-ui.{{.Task.Slot}}'
    environment:
       TERM: screen-256color
       LC_CTYPE: en_US.UTF-8
       LANG: en_US.UTF-8
    volumes:
      - type: bind
        source: ./monster-entrypoint.sh
        target: /monster-entrypoint.sh
      - type: bind
        source: ${MONSTER_PATH:-/home/hesaam/work/2600hz/kazoo/monster-ui}
        target: "/opt/monster-ui"
      - type: bind
        source: ${SU_EXEC_BIN:-/home/hesaam/work/2600hz/kazoo/su-exec/su-exec}
        target: "/su-exec"
    ports:
      - target: 3000
    tty: true
    entrypoint: /monster-entrypoint.sh
    command: ["/opt/monster-ui/node_modules/gulp/bin/gulp.js"]
    networks:
      kazoo:
        aliases:
          - 'monster-ui.{{.Task.Slot}}'

  # mailcatcher:
  #   image: 'schickling/mailcatcher'
  #   ports:
  #     - target: 1080
  #     - target: 1025
  #   networks:
  #     - kazoo

networks:
  kazoo:
    attachable: true

