version: '3.5'

x-node-env:
  &kz-env
    KAZOO_COOKIE: change_me
    LC_CTYPE: en_US.UTF-8
    LANG: en_US.UTF-8
    CODE_LOADING_MODE: interactive
    RELX_REPLACE_OS_VARS: "true"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/kazoo/app/_rel/kazoo/bin"

x-devnode-cfg:
  &kz-dev
    - type: bind
      source: ${KAZOO_SRC_PATH:-${HOME}/work/2600hz/kazoo/master}
      target: /opt/kazoo
      read_only: false
    - type: bind
      source: ./config.ini
      target: /etc/kazoo/config.ini
      read_only: true
    - type: bind
      source: ${KAZOO_SOUNDS_PATH:-${HOME}/work/2600hz/kazoo/sounds/kazoo-core}
      target: /opt/sounds
      read_only: true

services:

  couchdb:
    image: couchdb:latest
    hostname: 'couchdb-{{.Task.Slot}}.{{index .Service.Labels "com.docker.stack.namespace"}}'
    environment:
      NODENAME: 'couchdb-{{.Task.Slot}}.{{index .Service.Labels "com.docker.stack.namespace"}}'
    ports:
      - target: 9100
        mode: host
      - target: 5984
        mode: host
      - target: 5986
    deploy:
      mode: replicated
    volumes:
      - type: bind
        source: ./couchdb_cluster.ini
        target: /opt/couchdb/etc/local.d/cluster.ini
      - type: bind
        source: "./data/"
        target: "/opt/couchdb/data"
      # - type: ${COUCHDB_VOL_TYPE:-tmpfs}
      #   target: ${COUCHDB_VOL_TARGET:-/opt/couchdb/data}
    networks:
      - kazoo

  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq-{{.Task.Slot}}.{{index .Service.Labels "com.docker.stack.namespace"}}'
    ports:
      - target: 15672
        mode: host
    networks:
      - kazoo

  kazoo_apps:
    image: ${KZ_DEV_BASE_IMAGE:-kz-dev-base}
    environment:
       << : *kz-env
       KAZOO_NODE: apps
       NODE_NAME: apps
       REL: apps
       KAZOO_APPS: ${KAZOO_APPS:-"blackhole,callflow,cdr,conference,crossbar,fax,hangups,media_mgr,milliwatt,omnipresence,pivot,registrar,reorder,stepswitch,sysconf,tasks,teletype,trunkstore,webhooks"}
    volumes: *kz-dev
    ports:
      - target: 11500
        mode: host
      - target: 8000
        mode: host
      - target: 5555
        mode: host
    hostname: 'kazoo-{{.Task.Slot}}.{{index .Service.Labels "com.docker.stack.namespace"}}'
    tty: true
    command: ["bash"]
    networks:
      - kazoo

  kazoo_ecallmgr:
    image: ${KZ_DEV_BASE_IMAGE:-kz-dev-base}
    environment:
       << : *kz-env
       KAZOO_NODE: ecallmgr
       NODE_NAME: ecallmgr
       REL: ecallmgr
       KAZOO_APPS: "ecallmgr"
    hostname: 'callmgr-{{.Task.Slot}}.{{index .Service.Labels "com.docker.stack.namespace"}}'
    volumes: *kz-dev
    ports:
      - target: 11500
        mode: host
    command: ["bash"]
    tty: true
    networks:
      - kazoo

  mailcatcher:
    hostname: 'mailcatcher-{{.Task.Slot}}.{{index .Service.Labels "com.docker.stack.namespace"}}'
    image: 'schickling/mailcatcher'
    ports:
      - "1080"
      - "1025"
    networks:
      - kazoo

  networks:
    kazoo:
      attachable: true

