#!/bin/bash

###############################################################
#### Utility functions

section_header() {
    cat <<END
################################################################################
## $1
################################################################################
END
}

substdef() {
    cat <<-END

#!substdef "!$1!$2!g"
END
}

try_def() {
    cat <<-END

#!trydef $1
END
}

get_local_ip() {
    echo -n $(ip route get $(ip route show 0.0.0.0/0 | grep -oP 'via \K\S+') | grep -oP 'src \K\S+')
}

get_public_ip() {
    echo -n `(dig @ns1.google.com TXT o-o.myaddr.l.google.com +short -4 2> /dev/null) | sed s/\"//g`
}

###############################################################
#### General

## if you don't want to put every variable in this file in enviroment
## put them in the file below and mount it as in docker config or mount bind it.
## You can add extra settings to variable `EXTRA_SETTINGS` (for multiline use here document
## like this) and then it will be add to the end of the docker.cfg file
[ -f /docker-kam-cfg-sourcer ] && . /docker-kam-cfg-sourcer

if [ -z "$CFG_DIR" ]; then
    CFG_DIR="${KAM_CFG_DIR:-/etc/kazoo/kamailio}"
fi
LOCAL_CFG_FILE="$CFG_DIR/local.cfg"

###############################################################
#### IP and HOST NAME

# setting MY_IP_ADDRESS to route interface IP or host public IP address
USE_PUBLIC_IP="${USE_PUBLIC_IP:-false}"
MY_HOSTNAME="${MY_HOSTNAME:-`hostname -f`}"

if [ "$USE_PUBLIC_IP" = "true" ]; then
    ## TODO: error check dig command if the internet is not reachable
    MY_IP_ADDRESS=`get_public_ip`
else
    MY_IP_ADDRESS=${KAM_IP_ADDRESS:-`get_local_ip`}
fi

###############################################################
#### AMQP options

# primary ampq zone name
MY_AMQP_ZONE="${AMQP_ZONE:-local}"
# primary amqp url
MY_AMQP_URL="${MY_AMQP_URL:-amqp://guest:guest@127.0.0.1:5672}"
# other zone amqp urls (for multi zone)
AMQP_URL2="$AMQP_URL2"
AMQP_URL3="$AMQP_URL3"
AMQP_URL4="$AMQP_URL4"
AMQP_URL5="$AMQP_URL5"
AMQP_URL6="$AMQP_URL6"

multi_zone_amqp() {
    local zones=""
    [ -n "$AMQP_URL2" ] && zones="$zones`substdef "AMQP_URL2" "$AMQP_URL2"`"
    [ -n "$AMQP_URL3" ] && zones="$zones`substdef "AMQP_URL3" "$AMQP_URL3"`"
    [ -n "$AMQP_URL4" ] && zones="$zones`substdef "AMQP_URL4" "$AMQP_URL4"`"
    [ -n "$AMQP_URL5" ] && zones="$zones`substdef "AMQP_URL5" "$AMQP_URL5"`"
    [ -n "$AMQP_URL6" ] && zones="$zones`substdef "AMQP_URL6" "$AMQP_URL6"`"
    echo "$zones"
}
ZONES_URLS=`multi_zone_amqp`

###############################################################
#### Roles var

ENABLE_ANTIFLOOD_ROLE="${ENABLE_ANTIFLOOD_ROLE:-false}"
ENABLE_SIP_TRACE_ROLE="${ENABLE_SIP_TRACE_ROLE:-false}"
ENABLE_PRESENCE_NOTIFY_SYNC_ROLE="${ENABLE_PRESENCE_NOTIFY_SYNC_ROLE:-false}"
ENABLE_PUSHER_ROLE="${ENABLE_PUSHER_ROLE:-false}"
ENABLE_WEBSOCKET_ROLE="${ENABLE_WEBSOCKET_ROLE:-false}"

KZ_MULTI_HOMED="${KZ_MULTI_HOMED:-1}"
ENABLE_RAM_DISK="${ENABLE_RAM_DISK:-false}"

###############################################################
#### Roles options

## Trace
SIP_TRACE_URI="${SIP_TRACE_URI:-127.0.0.1:9060}"
HEP_CAPTURE_ID="${HEP_CAPTURE_ID:-2}"

## Websocket
MY_WEBSOCKET_DOMAIN="${MY_WEBSOCKET_DOMAIN:-$MY_HOSTNAME}"
WEBSOCKET_NO_ORIGIN_RESTRICTION="${WEBSOCKET_NO_ORIGIN_RESTRICTION:-false}"

###############################################################
#### Roles enabler

enable_roles() {
    local roles=""
    [ "$ENABLE_ANTIFLOOD_ROLE" = "true" ] && roles="$roles`try_def 'ANTIFLOOD_ROLE'`"
    [ "$ENABLE_SIP_TRACE_ROLE" = "true" ] && roles="$roles`try_def 'ENABLE_SIP_TRACE_ROLE'`"
    [ "$ENABLE_PRESENCE_NOTIFY_SYNC_ROLE" = "true" ] && roles="$roles`try_def 'ENABLE_PRESENCE_NOTIFY_SYNC_ROLE'`"
    [ "$ENABLE_PUSHER_ROLE" = "true" ] && roles="$roles`try_def 'ENABLE_PUSHER_ROLE'`"
    [ "$ENABLE_WEBSOCKET_ROLE" = "true" ] && roles="$roles`try_def 'ENABLE_WEBSOCKET_ROLE'`"

    echo "$roles"
}
ROLES_SECTION=`enable_roles`


###############################################################
#### Create settings strings

## SIP TRACE
sip_trace_settings() {
        cat <<-END
#!define SIP_TRACE_URI "sip:$SIP_TRACE_URI"
#!trydef HEP_CAPTURE_ID $HEP_CAPTURE_ID
#!trydef KZ_TRACE 1
END
}

if [ "$ENABLE_SIP_TRACE_ROLE" = "true" ]; then
    SIP_TRACE_SETTINGS=`sip_trace_settings`
fi

## WEBSOCKETS
websockets_settings() {
    local websockets=`substdef "MY_WEBSOCKET_DOMAIN" "$MY_WEBSOCKET_DOMAIN"`
    [ "$WEBSOCKET_NO_ORIGIN_RESTRICTION" = "true" ] && websockets="$websockets`try_def 'WEBSOCKET_NO_ORIGIN_RESTRICTION'`"
    echo "$websockets"
}
if [ "$ENABLE_WEBSOCKET_ROLE" = "true" ]; then
    WEBSOCKETS_SETTINGS=`websockets_settings`
fi


if [ x"$KZ_MULTI_HOMED" = x"0" ]; then
    KZ_MULTI_HOMED_SETTINGS="#!define KZ_MULTI_HOMED 0"
# elif [ x"$KZ_MULTI_HOMED" = x"1" ]; then
#     KZ_MULTI_HOMED_SETTINGS="#!define KZ_MULTI_HOMED 1"
fi

if [ "$ENABLE_RAM_DISK" = "true" ]; then
    ENABLE_RAM_DISK_SETTINGS="#enable_ram_disk = true"
fi

## import docker file
if [ "$(grep -co '"docker.cfg"' $CFG_DIR/local.cfg)" -eq 0 ]; then
    #sed -r -i '/defs\.cfg/i import_file "docker.cfg"' $CFG_DIR/local.cfg
    echo 'import_file "docker.cfg"' >> $CFG_DIR/local.cfg.bak
    echo >> $CFG_DIR/local.cfg.bak
    cat $CFG_DIR/local.cfg >> $CFG_DIR/local.cfg.bak
    mv $CFG_DIR/local.cfg.bak $CFG_DIR/local.cfg
fi

cat > /etc/kazoo/kamailio/docker.cfg <<-EOF
## NOTE: This file automatically generated by docker-kamailio and docker-entrypoint ##


######################################
## ROLES
######################################
${ROLES_SECTION:-# # # no roles enabled}

######################################
## SERVER INFORMATION
######################################
#!substdef "!MY_HOSTNAME!${MY_HOSTNAME}!g"
#!substdef "!MY_IP_ADDRESS!${MY_IP_ADDRESS}!g"

######################################
## PRIMARY AMQP INFORMATION
######################################
#!substdef "!MY_AMQP_ZONE!${MY_AMQP_ZONE}!g"
#!substdef "!MY_AMQP_URL!${MY_AMQP_URL}!g"

######################################
## ZONES AMQP INFORMATION
######################################
${ZONES_URLS:-# # # no amqp zones}

######################################
## WEBSOCKETS
######################################
${WEBSOCKETS_SETTINGS:-# # # websocket is not configured}

######################################
## SIP traffic mirroring to SIP_TRACE server
######################################
${SIP_TRACE_SETTINGS:-# # # sip_trace is not configured}

######################################
## KZ_MULTI_HOMED ANS RAM DISK
######################################
${KZ_MULTI_HOMED_SETTINGS:-# # # multihomed is not configured}
${ENABLE_RAM_DISK_SETTINGS:-# # # ram_disk is not configured}
EOF
