version: '3.7'

volumes:
    elastic-data:
        name: kz-elastic-data

services:
  elasticsearch:
    image: elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.monitoring.elasticsearch.collection.enabled=true
      - xpack.monitoring.collection.enabled=true
    volumes:
      - type: volume
        source: elastic-data
        target: /usr/share/elasticsearch/data
    network_mode: host
    # when not using network_mpde=host
    # ports:
    #   - target: 9200
    #   - target: 9300
    # networks:
    #   kazoo:

  kibana:
    image: kibana:7.3.1
    environment:
        - ELASTICSEARCH_HOSTS="http://localhost:9200"
        - XPACK_MONITORING_ENABLED=true
        - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true
    network_mode: host
    # when not using network_mpde=host
    # ports:
    #   - target: 5601
    # networks:
    #   kazoo:

  logstash:
    image: logstash:7.3.1
    environment:
        - XPACK_MONITORING_ENABLED=true
        - XPACK_MONITORING_ELASTICSEARCH_HOSTS="http://localhost:9200"
    volumes:
        - type: bind
          source: ./logstash.conf
          target: /usr/share/logstash/pipeline/logstash.conf
          read_only: true
    network_mode: host
    # when not using network_mpde=host
    # ports:
    #   - target: 12201
    # networks:
    #   kazoo:

  couchdb:
    image: couchdb:latest
    hostname: 'couchdb.hsm.com'
    environment:
      NODENAME: 'couchdb.hsm.com'
    volumes:
      - type: bind
        source: ${wWork}/dockerfiles/kazoo/stacks/all_kz/couchdb_cluster.ini
        target: /opt/couchdb/etc/local.d/20-cluster.ini
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://localhost:12201'
    network_mode: host
