version: '3.7'

x-node-env:
  &kz-env
    LOCAL_USER: "true"
    TERM: screen-256color
    KAZOO_COOKIE: change_me
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/kazoo/_rel/kazoo/bin"

x-devol-cfg:
  &kz-vol
    - type: bind
      source: ${wKazoo}/4.3
      target: /opt/kazoo
      read_only: false
    - type: bind
      source: ${wKazoo}/sounds/kazoo-core
      target: /opt/sounds
      read_only: true
    - type: bind
      source: ${wKazoo}/monster-ui
      target: /opt/monster-ui
      read_only: true
    - type: bind
      source: ${wWork}/dockerfiles/scripts
      target: /opt/scripts
      read_only: true
    - type: bind
      source: ./config.ini
      target: /etc/kazoo/config.ini

volumes:
    couchdb-data:
        name: kz-4.3-couchdb-data
    rabbit-4.3-data:
        name: kz-4.3-rabbit-data

services:
  couchdb:
    image: couchdb:latest
    hostname: 'couchdb.4.3.hsm.com'
    environment:
      NODENAME: 'couchdb.4.3.hsm.com'
    volumes:
      - type: bind
        source: ${wWork}/dockerfiles/kazoo/stacks/all_kz/couchdb_cluster.ini
        target: /opt/couchdb/etc/local.d/20-cluster.ini
      - type: volume
        source: couchdb-data
        target: "/opt/couchdb/data"
    network_mode: host
    # when not using network_mpde=host
    # ports:
    #   - target: 9100
    #   - target: 5984
    #     mode: host
    #   - target: 5986
    #     mode: host
    # networks:
    #   kazoo:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq.4.3.hsm.com'
    network_mode: host
    environment:
        RABBITMQ_USE_LONGNAME: 'true'
    volumes:
        - type: volume
          source: rabbit-4.3-data
          target: /var/lib/rabbitmq
    # when not using network_mpde=host
    # ports:
    #   - target: 15672 # management UI
    #     mode: host
    #   - target: 5672 # AMQP port
    #     mode: host
    # networks:
    #   kazoo:

  kazoo_apps:
    image: icehess/kz-dev-env:19
    hostname: 'kazoo_apps.4.3.hsm.com'
    environment:
       << : *kz-env
       KAZOO_NODE: kazoo_apps
       NODE_NAME: kazoo_apps
       REL: kazoo_apps
    volumes: *kz-vol
    tty: true
    command: ["bash"]
    network_mode: host
    # when not using network_mpde=host
    # ports:
    #   - target: 11500 # Erlang
    #     mode: host
    #   - target: 8000 # Crossbar
    #     mode: host
    #   - target: 5555 # Websocket
    #     mode: host
    #   - target: 25 # Fax SMTP
    #     mode: host
    #   - target: 8001 # GraphQL
    #     mode: host
    # networks:
    #   kazoo:

  kazoo_ecallmgr:
    image: icehess/kz-dev-env:19
    hostname: 'ecallmgr.4.3.hsm.com'
    environment:
       << : *kz-env
       KAZOO_NODE: ecallmgr
       NODE_NAME: ecallmgr
       REL: ecallmgr
       KAZOO_APPS: "ecallmgr"
    volumes: *kz-vol
    command: ["bash"]
    tty: true
    network_mode: host
    # when not using network_mpde=host
    # ports:
    #   - target: 11500
    #     mode: host
    # networks:
    #   kazoo:

  freeswitch:
    image: icehess/kz-fs:1.6.20-centos-unofficial
    hostname: 'freeswitch.4.3.hsm.com'
    command: /usr/bin/docker-freeswitch start
    environment:
        LOCAL_USER: "true"
    #    FS_TRACE: "true"
    network_mode: host
    # when not using network_mpde=host
    # networks:
    #   kazoo:

  kamailio:
    image: icehess/kz-kam:5.1.9-2600hz.rc0.2
    hostname: 'kamailio.4.3.hsm.com'
    command: /usr/bin/docker-kamailio start
    environment:
        LOCAL_USER: "true"
    #     ENABLE_SIP_TRACE_ROLE: "true"
    network_mode: host
    # when not using network_mpde=host
    # ports:
    #   - published: 5060 # SIP TCP
    #     target: 5060
    #     protocol: tcp
    #     mode: host
    #   - published: 5060 # SIP UDP
    #     target: 5060
    #     protocol: udp
    #     mode: host
    #   - published: 5061 # SSIP (SIP TLS)
    #     target: 5061
    #     protocol: tcp
    #     mode: host
    #   - published: 7000 # SIP ALG TCP
    #     target: 7000
    #     protocol: tcp
    #     mode: host
    #   - published: 7000 # SIP ALG UDP
    #     target: 7000
    #     protocol: udp
    #     mode: host
    #   - published: 7001 # SSIP ALG
    #     target: 7001
    #     protocol: tcp
    #     mode: host
    #   - published: 5064 # http/https/websocket
    #     target: 5064
    #     protocol: tcp
    #     mode: host
    #   - published: 5065 # http/https/websocket
    #     target: 5065
    #     protocol: tcp
    #     mode: host
    # networks:
    #   kazoo:

  monster-ui:
    image: ${MONSTER_IMG:-node:10.16.0-alpine}
    hostname: 'portal.4.3.hsm.com'
    environment:
       TERM: screen-256color
       LC_CTYPE: en_US.UTF-8
       LANG: en_US.UTF-8
    volumes:
      - type: bind
        source: ./monster-entrypoint.sh
        target: /monster-entrypoint.sh
      - type: bind
        source: ${wKazoo}/monster-ui
        target: "/opt/monster-ui"
    tty: true
    entrypoint: /monster-entrypoint.sh
    command: ["/opt/monster-ui/node_modules/gulp/bin/gulp.js", "serve-dev"]
    network_mode: host
    # when not using network_mpde=host
    # ports:
    #   - target: 3000
    #     mode: host
    # networks:
    #   kazoo:

  mailcatcher:
    image: 'schickling/mailcatcher'
    hostname: 'mail.4.3.hsm.com'
    network_mode: host
    # when not using network_mpde=host
    # ports:
    #   - target: 1080
    #     mode: host
    #   - target: 1025
    #     mode: host
    # networks:
    #   - kazoo

# networks:
#   kazoo:
#     attachable: true

